In [2]:
import torch

In [19]:
from torch.autograd import Variable
a=Variable(torch.tensor([[4.,5.],[7.,8.]]),requires_grad=True)

In [20]:
y=a**3+4*a**2+3*a+2
print(y)

tensor([[142., 242.],
        [562., 794.]], grad_fn=<AddBackward0>)


In [21]:
res=torch.sum(y)
res.backward()
print("Gradient is ",a.grad)

Gradient is  tensor([[ 83., 118.],
        [206., 259.]])


INVERSE OF MATRIX

In [10]:
a=torch.tensor([[1.3,4.5],[2.5,8.9]],dtype=torch.float32,requires_grad=True)
print(a)

tensor([[1.3000, 4.5000],
        [2.5000, 8.9000]], requires_grad=True)


In [11]:
inv=torch.inverse(a)
print(inv)

tensor([[ 27.8126, -14.0626],
        [ -7.8125,   4.0625]], grad_fn=<LinalgInvExBackward0>)


In [18]:
import torch.nn as nn
class inverse(nn.Module):
    def __init__(self):
        super(inverse,self).__init__()
    def forward(self,x):

        inv_res=torch.inverse(x)
        return inv_res
    
inverse_obj=inverse()
output=inverse_obj(a)

print(output)

tensor([[ 27.8126, -14.0626],
        [ -7.8125,   4.0625]], grad_fn=<LinalgInvExBackward0>)


In [24]:
a=1.3
b=4.5
c=2.5
d=8.9

ori=torch.tensor([[a,b],[c,d]])
mat1=torch.tensor([[d,-b],[-c,a]])/torch.det(ori)
print(mat1)

tensor([[ 27.8126, -14.0626],
        [ -7.8125,   4.0625]])


In [25]:
print("INVERSE OF 2X2 MATRIX")
lis=[]
for i in range(2):
    row=[]
    for j in range(2):
        val=int(input("Enter the element at {}{}".format(i,j)))
        row.append(val)
    lis.append(row)
print(lis)

INVERSE OF 2X2 MATRIX
[[3, 4], [5, 6]]


In [28]:
t=torch.tensor(lis,dtype=torch.float32)
det_val=torch.det(t)
print("Determinant of Matrix is ",det_val)
adj_t1=torch.tensor([[t[1][1],-t[0][1]],[-t[1][0],t[0][0]]])

Determinant of Matrix is  tensor(-2.)


In [29]:
print("Adjoint of matrix ")
print(adj_t1)

Adjoint of matrix 
tensor([[ 6., -4.],
        [-5.,  3.]])


In [30]:
inv=adj_t1/det_val
print("Inverse of Matrix is ",inv)

Inverse of Matrix is  tensor([[-3.0000,  2.0000],
        [ 2.5000, -1.5000]])


TENSOR OPERATIONS

In [4]:
t1=torch.tensor([[1,2,3],[4,5,6]])
t2=torch.tensor([[3,6,9],[1,5,7]])

sum_res = torch.add(t1, t2)
print("\nTensor Addition:")
print(sum_res)

# Element-wise multiplication
product_res = torch.mul(t1, t2)
print("\nElement-wise Multiplication:")
print(product_res)

print("\nSubration :",torch.sub(t1, t2))
print("\nDivision :",torch.div(t1, t2))



Tensor Addition:
tensor([[ 4,  8, 12],
        [ 5, 10, 13]])

Element-wise Multiplication:
tensor([[ 3, 12, 27],
        [ 4, 25, 42]])

Subration : tensor([[-2, -4, -6],
        [ 3,  0, -1]])

Division : tensor([[0.3333, 0.3333, 0.3333],
        [4.0000, 1.0000, 0.8571]])


In [6]:
t2_trans=t2.t()
print("\Matrix Multiplication :",torch.matmul(t1, t2_trans))

\Matrix Multiplication : tensor([[42, 32],
        [96, 71]])


In [14]:
torch.sum(t1,1)

tensor([ 6, 15])

In [15]:
torch.sqrt(t2)

tensor([[1.7321, 2.4495, 3.0000],
        [1.0000, 2.2361, 2.6458]])